/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "ApiProtos.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ApiResponseApps, ApiResponseApps, AUTO)


PB_BIND(ApiResponseAppsNano, ApiResponseAppsNano, AUTO)


PB_BIND(ApiResponseMediaImages, ApiResponseMediaImages, AUTO)


PB_BIND(ApiResponseMediaImageRefs, ApiResponseMediaImageRefs, AUTO)


PB_BIND(ApiResponseDownloadSystemState, ApiResponseDownloadSystemState, AUTO)


PB_BIND(ApiResponseUploadSystemState, ApiResponseUploadSystemState, AUTO)


PB_BIND(App, App, 2)


PB_BIND(AppNano, AppNano, AUTO)


PB_BIND(Trs80Extension, Trs80Extension, AUTO)


PB_BIND(MediaImage, MediaImage, AUTO)


PB_BIND(MediaImageRef, MediaImageRef, 2)


PB_BIND(SystemState, SystemState, AUTO)


PB_BIND(SystemState_Registers, SystemState_Registers, AUTO)


PB_BIND(SystemState_MemoryRegion, SystemState_MemoryRegion, AUTO)


PB_BIND(FetchMediaImagesParams, FetchMediaImagesParams, AUTO)


PB_BIND(FetchMediaImageRefsParams, FetchMediaImageRefsParams, AUTO)


PB_BIND(FetchMediaImageRegionParams, FetchMediaImageRegionParams, AUTO)


PB_BIND(GetAppParams, GetAppParams, AUTO)


PB_BIND(ListAppsParams, ListAppsParams, AUTO)


PB_BIND(ListAppsParams_Trs80Params, ListAppsParams_Trs80Params, AUTO)


PB_BIND(UploadSystemStateParams, UploadSystemStateParams, AUTO)


PB_BIND(DownloadSystemStateParams, DownloadSystemStateParams, AUTO)


PB_BIND(DownloadSystemStateMemoryRegionParams, DownloadSystemStateMemoryRegionParams, AUTO)





